site_name: Tiaki News
site_url: https://tiaki.pages.dev


theme:
  name: material

  palette:
    scheme: default
    accent: blue

  font:
    text: Ubuntu

  features:
  # nav features
    navigation.instant
    navigation.instant.progress
    navigation.tabs
    navigation.tabs.sticky
    navigation.sections
    navigation.path
    navigation.prune
    navigation.indexes
    navigation.top
    toc.follow

plugins:
 social:
  cards_layout_dir: layouts
  cards_layout: custom
  debug: true   






